-- +goose Up
-- Generated by scripts/pg-to-mysql/pg_to_mysql.py — DO NOT EDIT manually.
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(255),
  `mode_trainer_or_builder` VARCHAR(255),
  `account_type` VARCHAR(255),
  `credit_limit` INT,
  `payment_method_on_file` TINYINT(1),
  `security_disable` TINYINT(1),
  `transaction_previous_id` INT,
  `address_primary_id` INT,
  `primary_user_id` INT,
  `stripe_id` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `account_address_primary_id_fkey` FOREIGN KEY (`address_primary_id`) REFERENCES `address` (`id`),
  CONSTRAINT `account_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `account_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `account_primary_user_id_fkey` FOREIGN KEY (`primary_user_id`) REFERENCES `userbase` (`id`),
  CONSTRAINT `account_transaction_previous_id_fkey` FOREIGN KEY (`transaction_previous_id`) REFERENCES `transaction` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `action` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `kind` VARCHAR(255),
  `active` TINYINT(1),
  `archived` TINYINT(1),
  `status` VARCHAR(255),
  `template_id` INT,
  `workflow_id` INT,
  `is_root` TINYINT(1),
  `root_id` INT,
  `parent_id` INT,
  `child_primary_id` INT,
  `project_id` INT,
  `org_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `brain_kind` VARCHAR(255),
  `brain_run_visual` TINYINT(1),
  `brain_completion_directory_id` INT,
  `count_label_file_id` INT,
  `count` INT,
  `count_confidence_threshold` DOUBLE,
  `condition_operator` VARCHAR(255),
  `condition_left_operand` VARCHAR(255),
  `condition_right_operand` VARCHAR(255),
  `condition_true_exists` TINYINT(1),
  `condition_false_exists` TINYINT(1),
  `condition_true_action_id` INT,
  `condition_false_action_id` INT,
  `time_delay` INT,
  `email_send_to` VARCHAR(255),
  `email_subject` VARCHAR(255),
  `email_body` VARCHAR(255),
  `overlay_kind` VARCHAR(255),
  `overlay_text` VARCHAR(255),
  `overlay_image_id` INT,
  `overlay_position` VARCHAR(255),
  `overlay_size` VARCHAR(255),
  `overlay_label_file_id` INT,
  `url_to_post` VARCHAR(255),
  `secret_webhook` VARCHAR(255),
  `icon` VARCHAR(255),
  `description` VARCHAR(255),
  `trigger_data` JSON,
  `config_data` JSON,
  `completion_condition_data` JSON,
  `public_name` VARCHAR(255),
  `ordinal` INT,
  `output` JSON,
  `output_interface` JSON,
  `precondition` JSON,
  PRIMARY KEY (`id`),
  CONSTRAINT `action_template_id_fkey` FOREIGN KEY (`template_id`) REFERENCES `action_template` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `action_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `workflow_run_id` BIGINT,
  `file_id` BIGINT,
  `action_id` BIGINT,
  `kind` VARCHAR(255),
  `workflow_id` INT,
  `project_id` INT,
  `org_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `link_to_results` VARCHAR(255),
  `count` INT,
  `condition_true` TINYINT(1),
  `condition_false` TINYINT(1),
  `condition_result` TINYINT(1),
  `email_was_sent_to` VARCHAR(255),
  `email_subject` VARCHAR(255),
  `email_body` VARCHAR(255),
  `overlay_rendered_image_id` INT,
  `output` JSON,
  `status` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `action_event_action_id_fkey` FOREIGN KEY (`action_id`) REFERENCES `action` (`id`),
  CONSTRAINT `action_event_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `action_event_flow_event_id_fkey` FOREIGN KEY (`workflow_run_id`) REFERENCES `workflow_run` (`id`),
  CONSTRAINT `action_event_flow_id_fkey` FOREIGN KEY (`workflow_id`) REFERENCES `workflow` (`id`),
  CONSTRAINT `action_event_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `org` (`id`),
  CONSTRAINT `action_event_overlay_rendered_image_id_fkey` FOREIGN KEY (`overlay_rendered_image_id`) REFERENCES `image` (`id`),
  CONSTRAINT `action_event_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__action_run_action_id` ON `action_run` (`action_id`);
CREATE INDEX `index__action_run_project_id` ON `action_run` (`project_id`);
CREATE INDEX `index__action_run_project_id_action_id` ON `action_run` (`project_id`, `action_id`);

CREATE TABLE IF NOT EXISTS `workflow_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255),
  `status_description` VARCHAR(255),
  `file_id` BIGINT,
  `workflow_id` INT,
  `project_id` INT,
  `org_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `link_to_results` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `action_flow_event_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `action_flow_event_flow_id_fkey` FOREIGN KEY (`workflow_id`) REFERENCES `workflow` (`id`),
  CONSTRAINT `action_flow_event_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `org` (`id`),
  CONSTRAINT `action_flow_event_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workflow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `string_id` VARCHAR(255),
  `trigger_type` VARCHAR(255),
  `time_window` VARCHAR(255),
  `active` TINYINT(1),
  `archived` TINYINT(1),
  `is_new` TINYINT(1),
  `kind` VARCHAR(255),
  `count_events` INT,
  `directory_id` INT,
  `first_action_id` BIGINT,
  `last_action_id` BIGINT,
  `project_id` INT,
  `org_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workflow_trigger_event_queue` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255),
  `input_id` INT,
  `has_aggregation_event_running` TINYINT(1),
  `aggregation_window_start_time` DATETIME(6),
  `project_id` INT,
  `task_id` INT,
  `job_id` INT,
  `workflow_id` INT,
  `org_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `member_created_id` INT,
  `member_updated_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `action_flow_id_fkey` FOREIGN KEY (`workflow_id`) REFERENCES `workflow` (`id`),
  CONSTRAINT `input_id_fkey` FOREIGN KEY (`input_id`) REFERENCES `input` (`id`),
  CONSTRAINT `job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `task` (`id`),
  CONSTRAINT `org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `org` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `action_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `public_name` VARCHAR(255),
  `kind` VARCHAR(255),
  `category` VARCHAR(255),
  `is_available` TINYINT(1),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `icon` VARCHAR(255),
  `description` VARCHAR(255),
  `trigger_data` JSON,
  `condition_data` JSON,
  `completion_condition_data` JSON,
  `is_global` TINYINT(1),
  PRIMARY KEY (`id`),
  CONSTRAINT `action_template_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `action_template_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `activity_interpolation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instance_group_list` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `line_1` VARCHAR(255),
  `line_2` VARCHAR(255),
  `line_3` VARCHAR(255),
  `line_4` VARCHAR(255),
  `locality` VARCHAR(255),
  `region` VARCHAR(255),
  `postcode` VARCHAR(255),
  `country` VARCHAR(255),
  `previous_address_id` INT,
  `member_created_id` INT,
  `time_created` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `address_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `address_previous_address_id_fkey` FOREIGN KEY (`previous_address_id`) REFERENCES `address` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `alembic_version` (
  `version_num` VARCHAR(255),
  PRIMARY KEY (`version_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `attribute_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT,
  `archived` TINYINT(1),
  `display_order` INT,
  `name` VARCHAR(255),
  `kind` VARCHAR(255),
  `value_type` VARCHAR(255),
  `project_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `parent_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `attribute_template_group_id_fkey` FOREIGN KEY (`group_id`) REFERENCES `attribute_template_group` (`id`),
  CONSTRAINT `attribute_template_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `attribute_template_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `attribute_template_parent_id_fkey` FOREIGN KEY (`parent_id`) REFERENCES `attribute_template` (`id`),
  CONSTRAINT `attribute_template_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `ix_attribute_template_group_id` ON `attribute_template` (`group_id`);

CREATE TABLE IF NOT EXISTS `attribute_template_group` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `archived` TINYINT(1),
  `name` VARCHAR(255),
  `prompt` VARCHAR(255),
  `show_prompt` TINYINT(1),
  `is_root` TINYINT(1),
  `is_new` TINYINT(1),
  `parent_id` INT,
  `root_id` INT,
  `kind` VARCHAR(255),
  `project_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `default_external_map_id` INT,
  `default_value` VARCHAR(255),
  `default_id` INT,
  `min_value` INT,
  `max_value` INT,
  `is_global` TINYINT(1),
  `global_type` VARCHAR(255),
  `ordinal` INT,
  `is_read_only` TINYINT(1),
  PRIMARY KEY (`id`),
  CONSTRAINT `attribute_template_group_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `attribute_template_group_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `attribute_template_group_parent_id_fkey` FOREIGN KEY (`parent_id`) REFERENCES `attribute_template` (`id`),
  CONSTRAINT `attribute_template_group_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `attribute_template_group_root_id_fkey` FOREIGN KEY (`root_id`) REFERENCES `attribute_template_group` (`id`),
  CONSTRAINT `default_external_map_id_fkey` FOREIGN KEY (`default_external_map_id`) REFERENCES `external_map` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `attribute_template_group_to_file` (
  `attribute_template_group_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  PRIMARY KEY (`attribute_template_group_id`, `file_id`),
  CONSTRAINT `attribute_template_group_to_fi_attribute_template_group_id_fkey` FOREIGN KEY (`attribute_template_group_id`) REFERENCES `attribute_template_group` (`id`),
  CONSTRAINT `attribute_template_group_to_file_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `audio_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `original_filename` VARCHAR(255),
  `description` VARCHAR(255),
  `soft_delete` TINYINT(1),
  `url_public` VARCHAR(255),
  `url_signed` VARCHAR(255),
  `url_signed_blob_path` VARCHAR(255),
  `url_signed_expiry` INT,
  `url_signed_expiry_force_refresh` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `auth_api` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT,
  `created_time` DATETIME(6),
  `client_id` VARCHAR(255),
  `client_secret` VARCHAR(255),
  `project_string_id` VARCHAR(255),
  `project_id` INT,
  `is_live` TINYINT(1),
  `is_valid` TINYINT(1),
  `permission_level` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `auth_api_member_id_fkey` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `auth_api_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `connection_base` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `archived` TINYINT(1),
  `is_active` TINYINT(1),
  `permission_scope` VARCHAR(255),
  `integration_name` VARCHAR(255),
  `integration_version` INT,
  `private_id` VARCHAR(255),
  `private_secret_encrypted` BLOB,
  `account_email` VARCHAR(255),
  `project_id_external` VARCHAR(255),
  `project_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `private_host` VARCHAR(255),
  `disabled_ssl_verify` TINYINT(1),
  `aws_v4_signature` TINYINT(1),
  `aws_region` VARCHAR(255),
  `url_signer_service` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `connection_base_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `connection_base_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `connection_base_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `credential` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `credential_type_id` INT,
  `user_id` INT,
  `status` VARCHAR(255),
  `external_id` VARCHAR(255),
  `image_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `credential_credential_type_id_fkey` FOREIGN KEY (`credential_type_id`) REFERENCES `credential_type` (`id`),
  CONSTRAINT `credential_image_id_fkey` FOREIGN KEY (`image_id`) REFERENCES `image` (`id`),
  CONSTRAINT `credential_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `credential_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `description_markdown` VARCHAR(255),
  `project_id` INT,
  `archived` TINYINT(1),
  `history_cache` VARCHAR(255),
  `public` TINYINT(1),
  `image_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `credential_type_image_id_fkey` FOREIGN KEY (`image_id`) REFERENCES `image` (`id`),
  CONSTRAINT `credential_type_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `credential_type_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `credential_type_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `credential_type_to_job` (
  `credential_type_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `kind` VARCHAR(255),
  PRIMARY KEY (`credential_type_id`, `job_id`),
  CONSTRAINT `credential_type_to_job_credential_type_id_fkey` FOREIGN KEY (`credential_type_id`) REFERENCES `credential_type` (`id`),
  CONSTRAINT `credential_type_to_job_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `dataset_tag` (
  `dataset_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `time_created` DATETIME(6),
  PRIMARY KEY (`dataset_id`, `tag_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `deletion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notes` VARCHAR(255),
  `mode` VARCHAR(255),
  `cache` VARCHAR(255),
  `project_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `deletion_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `deletion_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `discussion` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `title` VARCHAR(255),
  `description` VARCHAR(255),
  `member_created_id` INT,
  `project_id` INT,
  `status` VARCHAR(255),
  `type` VARCHAR(255),
  `marker_frame_number` INT,
  `marker_type` VARCHAR(255),
  `marker_data` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `discussion_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT,
  `discussion_id` INT,
  `project_id` INT,
  `content` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `discussion_id_fkey` FOREIGN KEY (`discussion_id`) REFERENCES `discussion` (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `discussion_member` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT,
  `member_id` INT,
  `discussion_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `discussion_id_fkey` FOREIGN KEY (`discussion_id`) REFERENCES `discussion` (`id`),
  CONSTRAINT `member_id_fkey` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `discussion_relation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `discussion_id` INT,
  `instance_id` INT,
  `file_id` INT,
  `job_id` INT,
  `type` VARCHAR(255),
  `project_id` INT,
  `task_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `discussion_id_fkey` FOREIGN KEY (`discussion_id`) REFERENCES `discussion` (`id`),
  CONSTRAINT `file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `instance_id_fkey` FOREIGN KEY (`instance_id`) REFERENCES `instance` (`id`),
  CONSTRAINT `job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `kind` VARCHAR(255),
  `description` VARCHAR(255),
  `success` TINYINT(1),
  `error_log` VARCHAR(255),
  `run_time` DOUBLE,
  `link` VARCHAR(255),
  `project_id` INT,
  `input_id` INT,
  `member_id` INT,
  `file_id` INT,
  `report_template_id` INT,
  `report_data` VARCHAR(255),
  `report_template_data` VARCHAR(255),
  `time_created` DATETIME(6),
  `task_id` INT,
  `job_id` INT,
  `object_type` VARCHAR(255),
  `page_name` VARCHAR(255),
  `install_fingerprint` VARCHAR(255),
  `diffgram_version` VARCHAR(255),
  `action_id` INT,
  `workflow_id` INT,
  `directory_id` INT,
  `extra_metadata` JSON,
  PRIMARY KEY (`id`),
  CONSTRAINT `event_action_id_fkey` FOREIGN KEY (`action_id`) REFERENCES `action` (`id`),
  CONSTRAINT `event_directory_id_fkey` FOREIGN KEY (`directory_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `event_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `event_input_id_fkey` FOREIGN KEY (`input_id`) REFERENCES `input` (`id`),
  CONSTRAINT `event_member_id_fkey` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `event_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `event_workflow_id_fkey` FOREIGN KEY (`workflow_id`) REFERENCES `workflow` (`id`),
  CONSTRAINT `job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `report_template_id_fkey` FOREIGN KEY (`report_template_id`) REFERENCES `report_template` (`id`),
  CONSTRAINT `task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_hub` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `kind` VARCHAR(255),
  `page_name` VARCHAR(255),
  `object_type` VARCHAR(255),
  `description` VARCHAR(255),
  `success` TINYINT(1),
  `error_log` VARCHAR(255),
  `run_time` DOUBLE,
  `link` VARCHAR(255),
  `project_id` INT,
  `input_id` INT,
  `task_id` INT,
  `task_template_id` INT,
  `member_id` INT,
  `file_id` INT,
  `report_template_id` INT,
  `report_data` VARCHAR(255),
  `report_template_data` VARCHAR(255),
  `time_created` DATETIME(6),
  `startup_time` DATETIME(6),
  `shut_down_time` DATETIME(6),
  `install_fingerprint` VARCHAR(255),
  `diffgram_version` VARCHAR(255),
  `previous_version` VARCHAR(255),
  `host_os` VARCHAR(255),
  `storage_backend` VARCHAR(255),
  `service_name` VARCHAR(255),
  `event_type` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `credentials_awarded` TINYINT(1),
  `user_taking_exam_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `exam_user_taking_exam_id_fkey` FOREIGN KEY (`user_taking_exam_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `export` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `type` VARCHAR(255),
  `kind` VARCHAR(255),
  `archived` TINYINT(1),
  `masks` TINYINT(1),
  `source` VARCHAR(255),
  `status` VARCHAR(255),
  `status_text` VARCHAR(255),
  `percent_complete` DOUBLE,
  `file_comparison_mode` VARCHAR(255),
  `file_list_length` INT,
  `description` VARCHAR(255),
  `working_dir_id` INT,
  `project_id` INT,
  `user_id` INT,
  `job_id` INT,
  `task_id` INT,
  `yaml_blob_name` VARCHAR(255),
  `json_blob_name` VARCHAR(255),
  `tf_records_blob_name` VARCHAR(255),
  `ann_is_complete` TINYINT(1),
  PRIMARY KEY (`id`),
  CONSTRAINT `export_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `export_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `export_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `export_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`),
  CONSTRAINT `export_working_dir_id_fkey` FOREIGN KEY (`working_dir_id`) REFERENCES `working_dir` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `external_map` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `external_id` VARCHAR(255),
  `type` VARCHAR(255),
  `diffgram_class_string` VARCHAR(255),
  `url` VARCHAR(255),
  `project_id` INT,
  `job_id` INT,
  `file_id` INT,
  `task_id` INT,
  `attribute_template_group_id` INT,
  `user_id` INT,
  `connection_id` INT,
  `dataset_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `instance_id` INT,
  `attribute_template_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `attribute_template_group_id_fkey` FOREIGN KEY (`attribute_template_group_id`) REFERENCES `attribute_template_group` (`id`),
  CONSTRAINT `external_map_attribute_template_id_fkey` FOREIGN KEY (`attribute_template_id`) REFERENCES `attribute_template` (`id`),
  CONSTRAINT `file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `instance_id_fkey` FOREIGN KEY (`instance_id`) REFERENCES `instance` (`id`),
  CONSTRAINT `job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `time_last_updated` DATETIME(6),
  `count_instances_changed` INT,
  `created_by_kind` VARCHAR(255),
  `time_committed` DATETIME(6),
  `job_id` INT,
  `input_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `state` VARCHAR(255),
  `committed` TINYINT(1),
  `type` VARCHAR(255),
  `hash` VARCHAR(255),
  `ann_is_complete` TINYINT(1),
  `has_some_machine_made_instances` TINYINT(1),
  `instance_type_count` VARCHAR(255),
  `boxes_count` INT,
  `boxes_machine_made_count` INT,
  `polygon_count` INT,
  `image_id` INT,
  `original_filename` VARCHAR(255),
  `video_id` INT,
  `video_parent_file_id` BIGINT,
  `is_child_of_video` TINYINT(1),
  `label_id` INT,
  `project_id` INT,
  `frame_number` INT,
  `global_frame_number` INT,
  `is_root` TINYINT(1),
  `root_id` BIGINT,
  `parent_id` BIGINT,
  `child_primary_id` BIGINT,
  `colour` VARCHAR(255),
  `mask_joint_blob_name` VARCHAR(255),
  `cache_dict` VARCHAR(255),
  `default_external_map_id` INT,
  `task_id` INT,
  `text_file_id` INT,
  `has_instances` TINYINT(1),
  `count_instances` INT,
  `file_metadata` JSON,
  `point_cloud_id` INT,
  `text_tokenizer` VARCHAR(255),
  `audio_file_id` INT,
  `connection_id` INT,
  `bucket_name` VARCHAR(255),
  `ui_schema_id` INT,
  `ordinal` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `audio_file_id_fkey` FOREIGN KEY (`audio_file_id`) REFERENCES `audio_file` (`id`),
  CONSTRAINT `default_external_map_id_fkey` FOREIGN KEY (`default_external_map_id`) REFERENCES `external_map` (`id`),
  CONSTRAINT `file_child_primary_id_fkey` FOREIGN KEY (`child_primary_id`) REFERENCES `file` (`id`),
  CONSTRAINT `file_connection_id_fkey` FOREIGN KEY (`connection_id`) REFERENCES `connection_base` (`id`),
  CONSTRAINT `file_image_id_fkey` FOREIGN KEY (`image_id`) REFERENCES `image` (`id`),
  CONSTRAINT `file_input_id_fkey` FOREIGN KEY (`input_id`) REFERENCES `input` (`id`),
  CONSTRAINT `file_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `file_label_id_fkey` FOREIGN KEY (`label_id`) REFERENCES `label` (`id`),
  CONSTRAINT `file_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `file_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `file_parent_id_fkey` FOREIGN KEY (`parent_id`) REFERENCES `file` (`id`),
  CONSTRAINT `file_point_cloud_id_fkey` FOREIGN KEY (`point_cloud_id`) REFERENCES `point_cloud` (`id`),
  CONSTRAINT `file_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `file_root_id_fkey` FOREIGN KEY (`root_id`) REFERENCES `file` (`id`),
  CONSTRAINT `file_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `file_video_id_fkey` FOREIGN KEY (`video_id`) REFERENCES `video` (`id`),
  CONSTRAINT `file_video_parent_file_id_fkey` FOREIGN KEY (`child_primary_id`) REFERENCES `file` (`id`),
  CONSTRAINT `text_file_id_fkey` FOREIGN KEY (`text_file_id`) REFERENCES `text_file` (`id`),
  CONSTRAINT `ui_schema_id_fkey` FOREIGN KEY (`ui_schema_id`) REFERENCES `ui_schema` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__file_original_filename` ON `file` (`original_filename`);
CREATE INDEX `index__parent_id` ON `file` (`parent_id`);
CREATE INDEX `index__parent_id_type` ON `file` (`parent_id`, `type`);
CREATE INDEX `index__project_id_parent_id_type` ON `file` (`project_id`, `state`, `parent_id`, `type`);
CREATE INDEX `index__video_parent_file_id__and__frame_number` ON `file` (`video_parent_file_id`, `frame_number`);
CREATE INDEX `index_file_project_id` ON `file` (`project_id`);
CREATE INDEX `index_file_project_id_state_project_type` ON `file` (`project_id`, `state`, `type`);
CREATE INDEX `index_file_state` ON `file` (`state`);
CREATE INDEX `index_project_ann_is_complete` ON `file` (`project_id`, `ann_is_complete`);
CREATE INDEX `index_project_created_time` ON `file` (`project_id`, `created_time`);

CREATE TABLE IF NOT EXISTS `file_stats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `count_instances` INT,
  `file_id` INT,
  `label_file_id` INT,
  `annotators_member_list` JSON,
  `attribute_value_text` VARCHAR(255),
  `attribute_value_number` INT,
  `attribute_value_selected` TINYINT(1),
  `attribute_value_selected_date` DATETIME(6),
  `attribute_value_selected_time` TIME,
  `attribute_template_id` INT,
  `attribute_template_group_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `file_stats_attribute_template_group_id_fkey` FOREIGN KEY (`attribute_template_group_id`) REFERENCES `attribute_template_group` (`id`),
  CONSTRAINT `file_stats_attribute_template_id_fkey` FOREIGN KEY (`attribute_template_id`) REFERENCES `attribute_template` (`id`),
  CONSTRAINT `file_stats_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `file_stats_label_file_id_fkey` FOREIGN KEY (`label_file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `file_stats_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `file_stats_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__fa_attribute_template_group_id` ON `file_stats` (`attribute_template_group_id`);
CREATE INDEX `index__fa_attribute_template_id` ON `file_stats` (`attribute_template_id`);
CREATE INDEX `index__fa_attributes` ON `file_stats` (`attribute_template_id`, `attribute_template_group_id`);
CREATE INDEX `index__fa_attributes_date` ON `file_stats` (`attribute_template_id`, `attribute_template_group_id`, `attribute_value_selected_date`);
CREATE INDEX `index__fa_attributes_selected` ON `file_stats` (`attribute_template_id`, `attribute_template_group_id`, `attribute_value_selected`);
CREATE INDEX `index__fa_attributes_text` ON `file_stats` (`attribute_template_id`, `attribute_template_group_id`, `attribute_value_text`);
CREATE INDEX `index__fa_label_file_id` ON `file_stats` (`label_file_id`);
CREATE INDEX `index__fa_label_file_id_count_instances` ON `file_stats` (`label_file_id`, `count_instances`);
CREATE INDEX `index__fa_member_list` ON `file_stats` (`annotators_member_list`);

CREATE TABLE IF NOT EXISTS `geo_asset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `original_filename` VARCHAR(255),
  `description` VARCHAR(255),
  `soft_delete` TINYINT(1),
  `url_signed` VARCHAR(255),
  `type` VARCHAR(255),
  `url_signed_blob_path` VARCHAR(255),
  `url_signed_expiry` VARCHAR(255),
  `file_id` INT,
  `project_id` INT,
  `url_signed_expiry_force_refresh` VARCHAR(255),
  `service_name` VARCHAR(255),
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `geo_asset_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `geo_asset_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__geo_asset_file_id` ON `geo_asset` (`file_id`);
CREATE INDEX `index__geo_asset_project_file` ON `geo_asset` (`project_id`, `file_id`);
CREATE INDEX `index__geo_asset_project_id` ON `geo_asset` (`project_id`);

CREATE TABLE IF NOT EXISTS `guide` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_visible` TINYINT(1),
  `archived` TINYINT(1),
  `name` VARCHAR(255),
  `description_markdown` VARCHAR(255),
  `history_cache` VARCHAR(255),
  `project_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `guide_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `guide_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `guide_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `original_filename` VARCHAR(255),
  `description` VARCHAR(255),
  `width` INT,
  `height` INT,
  `soft_delete` TINYINT(1),
  `mask_joint_url` VARCHAR(255),
  `mask_joint_blob_name` VARCHAR(255),
  `is_inference` TINYINT(1),
  `annotation_status` VARCHAR(255),
  `is_annotation_example` TINYINT(1),
  `url_annotation_example` VARCHAR(255),
  `url_annotation_example_thumb` VARCHAR(255),
  `url_public` VARCHAR(255),
  `url_public_thumb` VARCHAR(255),
  `url_signed` VARCHAR(255),
  `url_signed_blob_path` VARCHAR(255),
  `url_signed_thumb` VARCHAR(255),
  `url_signed_thumb_blob_path` VARCHAR(255),
  `url_signed_expiry` INT,
  `url_signed_expiry_force_refresh` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `rotation_degrees` INT,
  `error` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `input` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `time_completed` DATETIME(6),
  `time_loaded_video` DATETIME(6),
  `time_video_write_finished` DATETIME(6),
  `time_pushed_all_frames_to_queue` DATETIME(6),
  `time_updated` DATETIME(6),
  `time_last_attempted` INT,
  `mode` VARCHAR(255),
  `url` VARCHAR(255),
  `media_type` VARCHAR(255),
  `type` VARCHAR(255),
  `allow_csv` TINYINT(1),
  `processing_deferred` TINYINT(1),
  `status` VARCHAR(255),
  `status_text` VARCHAR(255),
  `offset_in_seconds` INT,
  `percent_complete` DOUBLE,
  `description` VARCHAR(255),
  `size` INT,
  `archived` TINYINT(1),
  `raw_data_blob_path` VARCHAR(255),
  `update_log` VARCHAR(255),
  `resumable_url` VARCHAR(255),
  `video_split_duration` INT,
  `video_was_split` TINYINT(1),
  `retry_log` VARCHAR(255),
  `retry_count` INT,
  `parent_input_id` INT,
  `parent_file_id` INT,
  `file_id` INT,
  `job_id` INT,
  `directory_id` INT,
  `invalid_directory_permission` TINYINT(1),
  `project_id` INT,
  `user_id` INT,
  `temp_dir` VARCHAR(255),
  `temp_dir_path_and_filename` VARCHAR(255),
  `dzuuid` VARCHAR(255),
  `original_filename` VARCHAR(255),
  `extension` VARCHAR(255),
  `instance_list` VARCHAR(255),
  `frame_packet_map` VARCHAR(255),
  `video_parent_length` INT,
  `task_id` INT,
  `task_action` VARCHAR(255),
  `external_map_id` INT,
  `external_map_action` VARCHAR(255),
  `newly_copied_file_id` INT,
  `source_directory_id` INT,
  `add_link` TINYINT(1),
  `remove_link` TINYINT(1),
  `copy_instance_list` TINYINT(1),
  `sequence_map` VARCHAR(255),
  `batch_id` INT,
  `allow_duplicates` TINYINT(1),
  `upload_aws_id` VARCHAR(255),
  `upload_aws_parts_list` VARCHAR(255),
  `upload_azure_block_list` VARCHAR(255),
  `file_metadata` JSON,
  `member_created_id` INT,
  `member_updated_id` INT,
  `auto_correct_instances_from_image_metadata` TINYINT(1),
  `image_metadata` JSON,
  `connection_id` INT,
  `bucket_name` VARCHAR(255),
  `ordinal` INT,
  `text_data` VARCHAR(255),
  `workflow_trigger_id` INT,
  `action_trigger_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `batch_id_fkey` FOREIGN KEY (`batch_id`) REFERENCES `input_batch` (`id`),
  CONSTRAINT `external_map_id_fkey` FOREIGN KEY (`external_map_id`) REFERENCES `external_map` (`id`),
  CONSTRAINT `input_action_trigger_id_fkey` FOREIGN KEY (`action_trigger_id`) REFERENCES `action` (`id`),
  CONSTRAINT `input_connection_id_fkey` FOREIGN KEY (`connection_id`) REFERENCES `connection_base` (`id`),
  CONSTRAINT `input_directory_id_fkey` FOREIGN KEY (`directory_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `input_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `input_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `input_parent_file_id_fkey` FOREIGN KEY (`parent_file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `input_parent_input_id_fkey` FOREIGN KEY (`parent_input_id`) REFERENCES `input` (`id`),
  CONSTRAINT `input_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `input_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`),
  CONSTRAINT `input_workflow_trigger_id_fkey` FOREIGN KEY (`workflow_trigger_id`) REFERENCES `workflow` (`id`),
  CONSTRAINT `newly_copied_file_id_fkey` FOREIGN KEY (`newly_copied_file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `source_directory_id_fkey` FOREIGN KEY (`source_directory_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__input_archived` ON `input` (`archived`);
CREATE INDEX `index__input_mode` ON `input` (`mode`);
CREATE INDEX `index__input_processing_deferred` ON `input` (`processing_deferred`);
CREATE INDEX `index__input_project_id` ON `input` (`project_id`);
CREATE INDEX `index__input_status` ON `input` (`status`);
CREATE INDEX `index__processing_deferred__archived` ON `input` (`processing_deferred`, `archived`);
CREATE INDEX `ix_input_project_id` ON `input` (`project_id`);

CREATE TABLE IF NOT EXISTS `input_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255),
  `percent_complete` DOUBLE,
  `source_directory_id` INT,
  `directory_id` INT,
  `project_id` INT NOT NULL,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_completed` DATETIME(6),
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `pre_labeled_data` VARCHAR(255),
  `data_temp_dir` VARCHAR(255),
  `upload_aws_id` VARCHAR(255),
  `upload_aws_parts_list` VARCHAR(255),
  `upload_azure_block_list` VARCHAR(255),
  `download_status_pre_labeled_data` VARCHAR(255),
  `download_log_pre_labeled_data` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `directory_id_fkey` FOREIGN KEY (`directory_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `source_directory_id_fkey` FOREIGN KEY (`source_directory_id`) REFERENCES `working_dir` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `instance` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `last_updated_time` DATETIME(6),
  `project_id` INT,
  `type` VARCHAR(255),
  `hash` VARCHAR(255),
  `status` VARCHAR(255),
  `sequence_id` INT,
  `number` INT,
  `frame_number` INT,
  `global_frame_number` INT,
  `machine_made` TINYINT(1),
  `interpolated` TINYINT(1),
  `verified` TINYINT(1),
  `soft_delete` TINYINT(1),
  `label_file_id` INT,
  `file_id` INT,
  `points` VARCHAR(255),
  `mask_url` VARCHAR(255),
  `mask_blob_dir` VARCHAR(255),
  `mask_url_expiry` INT,
  `x_min` INT,
  `y_min` INT,
  `x_max` INT,
  `y_max` INT,
  `width` INT,
  `height` INT,
  `preview_image_url` VARCHAR(255),
  `preview_image_blob_dir` VARCHAR(255),
  `preview_image_url_expiry` INT,
  `rating` INT,
  `rating_comment` VARCHAR(255),
  `attribute_groups` VARCHAR(255),
  `member_created_id` INT,
  `task_id` INT,
  `start_sentence` INT,
  `end_sentence` INT,
  `start_token` INT,
  `end_token` INT,
  `start_char` INT,
  `end_char` INT,
  `sentence` INT,
  `parent_file_id` INT,
  `creation_ref_id` VARCHAR(255),
  `previous_id` BIGINT,
  `next_id` BIGINT,
  `root_id` BIGINT,
  `version` INT,
  `front_face` VARCHAR(255),
  `rear_face` VARCHAR(255),
  `angle` DOUBLE,
  `center_x` INT,
  `center_y` INT,
  `p1` VARCHAR(255),
  `p2` VARCHAR(255),
  `cp` VARCHAR(255),
  `deleted_time` DATETIME(6),
  `nodes` VARCHAR(255),
  `edges` VARCHAR(255),
  `is_template` TINYINT(1),
  `client_created_time` DATETIME(6),
  `change_source` VARCHAR(255),
  `deletion_type` VARCHAR(255),
  `action_type` VARCHAR(255),
  `pause_object` TINYINT(1),
  `model_id` INT,
  `model_run_id` INT,
  `rotation_euler_angles` VARCHAR(255),
  `position_3d` VARCHAR(255),
  `center_3d` VARCHAR(255),
  `max_point_3d` VARCHAR(255),
  `min_point_3d` VARCHAR(255),
  `dimensions_3d` VARCHAR(255),
  `text_tokenizer` VARCHAR(255),
  `from_instance_id` INT,
  `to_instance_id` INT,
  `lonlat` JSON,
  `coords` JSON,
  `radius` DOUBLE,
  `bounds` JSON,
  `bounds_lonlat` JSON,
  `start_time` DOUBLE,
  `end_time` DOUBLE,
  `score` DOUBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `instance_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `instance_from_instance_id_fkey` FOREIGN KEY (`from_instance_id`) REFERENCES `instance` (`id`),
  CONSTRAINT `instance_label_file_id_fkey` FOREIGN KEY (`label_file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `instance_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `instance_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `instance_sequence_id_fkey` FOREIGN KEY (`sequence_id`) REFERENCES `sequence` (`id`),
  CONSTRAINT `instance_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `instance_to_instance_id_fkey` FOREIGN KEY (`to_instance_id`) REFERENCES `instance` (`id`),
  CONSTRAINT `model_id_fkey` FOREIGN KEY (`model_id`) REFERENCES `model` (`id`),
  CONSTRAINT `model_run_id_fkey` FOREIGN KEY (`model_run_id`) REFERENCES `model_run` (`id`),
  CONSTRAINT `parent_file_id_fkey` FOREIGN KEY (`parent_file_id`) REFERENCES `file` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__created_time` ON `instance` (`created_time`);
CREATE INDEX `index__file_id__and__frame_number` ON `instance` (`file_id`, `frame_number`);
CREATE INDEX `index__file_id__and__label_id` ON `instance` (`file_id`, `label_file_id`);
CREATE INDEX `index__file_id_label_file_id` ON `instance` (`file_id`, `label_file_id`);
CREATE INDEX `index__instance_root_id` ON `instance` (`root_id`);
CREATE INDEX `index__parent_file_id_label_file_id` ON `instance` (`parent_file_id`, `label_file_id`);
CREATE INDEX `index__parent_id__and__label_id` ON `instance` (`parent_file_id`, `label_file_id`);
CREATE INDEX `index__sequence_id__and__soft_delete` ON `instance` (`sequence_id`, `soft_delete`);
CREATE INDEX `index__task_id` ON `instance` (`task_id`);
CREATE INDEX `index__task_id_label_file_id` ON `instance` (`task_id`, `label_file_id`);
CREATE INDEX `index_project_id_created_time_soft_delete` ON `instance` (`project_id`, `created_time`, `soft_delete`);
CREATE INDEX `index_project_id_soft_delete` ON `instance` (`project_id`, `soft_delete`);

CREATE TABLE IF NOT EXISTS `instance_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `project_id` INT,
  `reference_width` INT,
  `reference_height` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `status` VARCHAR(255),
  `created_time` DATETIME(6),
  `last_updated_time` DATETIME(6),
  `deleted_time` DATETIME(6),
  `mode` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `instance_template_relation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `instance_id` INT,
  `instance_template_id` INT,
  `created_time` DATETIME(6),
  `last_updated_time` DATETIME(6),
  `deleted_time` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `instance_id_fkey` FOREIGN KEY (`instance_id`) REFERENCES `instance` (`id`),
  CONSTRAINT `instance_template_id_fkey` FOREIGN KEY (`instance_template_id`) REFERENCES `instance_template` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hidden` TINYINT(1),
  `is_live` TINYINT(1),
  `td_api_trainer_basic_training` TINYINT(1),
  `quality_score_last` DOUBLE,
  `attached_directories_dict` VARCHAR(255),
  `auction_rank_last` INT,
  `auction_cost_per_instance_last` INT,
  `security_require_email_verified` TINYINT(1),
  `status` VARCHAR(255),
  `type` VARCHAR(255),
  `is_template` TINYINT(1),
  `instance_type` VARCHAR(255),
  `share_type` VARCHAR(255),
  `permission` VARCHAR(255),
  `project_id` INT,
  `category` VARCHAR(255),
  `guide_default_id` INT,
  `guide_review_id` INT,
  `directory_id` INT,
  `completion_directory_id` INT,
  `completion_action` VARCHAR(255),
  `review_by_human_freqeuncy` VARCHAR(255),
  `label_mode` VARCHAR(255),
  `passes_per_file` INT,
  `file_count` INT,
  `launch_datetime_deferred` DATETIME(6),
  `launch_datetime` DATETIME(6),
  `launch_attempt_log` VARCHAR(255),
  `waiting_to_be_launched` TINYINT(1),
  `label_dict` VARCHAR(255),
  `name` VARCHAR(255),
  `description` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `time_completed` DATETIME(6),
  `stat_last_updated_time` INT,
  `file_count_statistic` INT,
  `stat_count_tasks` INT,
  `stat_count_complete` INT,
  `stat_count_labels` INT,
  `is_root` TINYINT(1),
  `root_id` INT,
  `parent_id` INT,
  `repeatable` TINYINT(1),
  `file_handling` VARCHAR(255),
  `output_dir_action` VARCHAR(255),
  `pending_initial_dir_sync` TINYINT(1),
  `interface_connection_id` INT,
  `default_external_map_id` INT,
  `cache_dict` VARCHAR(255),
  `send_tasks_to_external_provider_on_launch` TINYINT(1),
  `pro_network` TINYINT(1),
  `is_pinned` TINYINT(1),
  `default_userscript_id` INT,
  `ui_schema_id` INT,
  `allow_reviews` TINYINT(1),
  `review_chance` DOUBLE,
  `exam_id` INT,
  `label_schema_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `default_external_map_id_fkey` FOREIGN KEY (`default_external_map_id`) REFERENCES `external_map` (`id`),
  CONSTRAINT `interface_connection_id_fkey` FOREIGN KEY (`interface_connection_id`) REFERENCES `connection_base` (`id`),
  CONSTRAINT `job_completion_directory_id_fkey` FOREIGN KEY (`completion_directory_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `job_directory_id_fkey` FOREIGN KEY (`directory_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `job_exam_id_fkey` FOREIGN KEY (`exam_id`) REFERENCES `exam` (`id`),
  CONSTRAINT `job_guide_default_id_fkey` FOREIGN KEY (`guide_default_id`) REFERENCES `guide` (`id`),
  CONSTRAINT `job_guide_review_id_fkey` FOREIGN KEY (`guide_review_id`) REFERENCES `guide` (`id`),
  CONSTRAINT `job_label_schema_id_fkey` FOREIGN KEY (`label_schema_id`) REFERENCES `label_schema` (`id`),
  CONSTRAINT `job_member_created_id_fkey` FOREIGN KEY (`guide_review_id`) REFERENCES `guide` (`id`),
  CONSTRAINT `job_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `job_parent_id_fkey` FOREIGN KEY (`parent_id`) REFERENCES `job` (`id`),
  CONSTRAINT `job_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `job_root_id_fkey` FOREIGN KEY (`root_id`) REFERENCES `job` (`id`),
  CONSTRAINT `ui_schema_id_fk` FOREIGN KEY (`ui_schema_id`) REFERENCES `ui_schema` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__job_project_id` ON `job` (`project_id`, `status`);

CREATE TABLE IF NOT EXISTS `job_launch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `job_id` INT,
  `retry_count` INT,
  `percent_complete` INT,
  `status` VARCHAR(255),
  `job_launch_info` VARCHAR(255),
  `log` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_intial_setup_completed` DATETIME(6),
  `time_updated` DATETIME(6),
  `time_completed` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `job_id_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `job_launch_queue` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `job_launch_id` INT,
  `priority` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `job_launch_id_fkey` FOREIGN KEY (`job_launch_id`) REFERENCES `job_launch` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `job_tag` (
  `job_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `time_created` DATETIME(6),
  PRIMARY KEY (`job_id`, `tag_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `job_working_dir` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `job_id` INT,
  `sync_type` VARCHAR(255),
  `working_dir_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `working_dir_id_fkey` FOREIGN KEY (`working_dir_id`) REFERENCES `working_dir` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `colour` VARCHAR(255),
  `soft_delete` TINYINT(1),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `label_schema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `project_id` INT,
  `archived` TINYINT(1),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `is_default` TINYINT(1),
  PRIMARY KEY (`id`),
  CONSTRAINT `label_schema_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `label_schema_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `label_schema_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index_label_schema_project_id` ON `label_schema` (`project_id`);

CREATE TABLE IF NOT EXISTS `label_schema_link` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schema_id` INT,
  `label_file_id` INT,
  `instance_template_id` INT,
  `attribute_template_group_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `label_schema_link_attribute_template_group_id_fkey` FOREIGN KEY (`attribute_template_group_id`) REFERENCES `attribute_template_group` (`id`),
  CONSTRAINT `label_schema_link_instance_template_id_fkey` FOREIGN KEY (`instance_template_id`) REFERENCES `instance_template` (`id`),
  CONSTRAINT `label_schema_link_label_file_id_fkey` FOREIGN KEY (`label_file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `label_schema_link_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `label_schema_link_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `label_schema_link_schema_id_fkey` FOREIGN KEY (`schema_id`) REFERENCES `label_schema` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index_label_schema_link_label_file_id` ON `label_schema_link` (`label_file_id`);
CREATE INDEX `index_label_schema_link_schema_id` ON `label_schema_link` (`schema_id`);

CREATE TABLE IF NOT EXISTS `member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kind` VARCHAR(255),
  `user_id` INT,
  `auth_api_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `member_auth_api_id_fkey` FOREIGN KEY (`auth_api_id`) REFERENCES `auth_api` (`id`),
  CONSTRAINT `member_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `model` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `last_updated_time` DATETIME(6),
  `deleted_time` DATETIME(6),
  `reference_id` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `project_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `model_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `last_updated_time` DATETIME(6),
  `deleted_time` DATETIME(6),
  `reference_id` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `project_id` INT,
  `model_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `model_id_fkey` FOREIGN KEY (`model_id`) REFERENCES `model` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255),
  `type` VARCHAR(255),
  `channel_type` VARCHAR(255),
  `title` VARCHAR(255),
  `description` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `notification_relation_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `notification_relation_id_fkey` FOREIGN KEY (`notification_relation_id`) REFERENCES `notification_relation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notification_relation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` INT,
  `input_id` INT,
  `job_id` INT,
  `task_id` INT,
  `member_id` INT,
  `file_id` INT,
  `working_dir_id` INT,
  `notification_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `input_id_fkey` FOREIGN KEY (`input_id`) REFERENCES `input` (`id`),
  CONSTRAINT `job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `member_id_fkey` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `notification_id_fkey` FOREIGN KEY (`notification_id`) REFERENCES `notification` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `working_dir_id_fkey` FOREIGN KEY (`working_dir_id`) REFERENCES `working_dir` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notification_user` (
  `notification_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `is_read` TINYINT(1),
  `time_created` DATETIME(6),
  PRIMARY KEY (`notification_id`, `user_id`),
  CONSTRAINT `notification_id_fkey` FOREIGN KEY (`notification_id`) REFERENCES `notification` (`id`),
  CONSTRAINT `user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `org` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `security_disable` TINYINT(1),
  `verified_by_diffgram` TINYINT(1),
  `name` VARCHAR(255),
  `api_address_valid` TINYINT(1),
  `api_trainer_org` TINYINT(1),
  `address_primary_id` INT,
  `primary_user_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `remote_address_created` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `org_address_primary_id_fkey` FOREIGN KEY (`address_primary_id`) REFERENCES `address` (`id`),
  CONSTRAINT `org_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `org_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `org_primary_user_id_fkey` FOREIGN KEY (`primary_user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `org_to_user` (
  `org_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_permission_level` VARCHAR(255),
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`org_id`, `user_id`),
  CONSTRAINT `org_to_user_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `org` (`id`),
  CONSTRAINT `org_to_user_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `template_id` INT,
  `is_active` TINYINT(1),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_ended` DATETIME(6),
  `time_updated` DATETIME(6),
  `premium_plan_user_count` INT,
  `is_annual_pricing` TINYINT(1),
  `calculated_charge` INT,
  `per_user_final` INT,
  `marketing_promo_code` VARCHAR(255),
  `marketing_promo_rate_found` DOUBLE,
  `marketing_plan_rate` INT,
  `marketing_savings` INT,
  `marketing_total` INT,
  `roi_monthly_engineering_cost` INT,
  `roi_monthly_supervisor_cost` INT,
  `roi_project_value` INT,
  `roi_eng_automation_benefit` DOUBLE,
  `roi_annotation_productivity_benefit` DOUBLE,
  `roi_project_quality_improvement` DOUBLE,
  `roi_total_benefit` INT,
  `roi_multiple` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `plan_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `plan_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `plan_template_id_fkey` FOREIGN KEY (`template_id`) REFERENCES `plan_template` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `plan_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `public_name` VARCHAR(255),
  `internal_name` VARCHAR(255),
  `kind` VARCHAR(255),
  `limit_instances` INT,
  `limit_projects` INT,
  `limit_files` INT,
  `limit_users_per_project` INT,
  `limit_video_frames_per_file` INT,
  `included_monthly_training_credits` INT,
  `cost_monthly` INT,
  `may_buy_instances` TINYINT(1),
  `cost_per_1000_instances` INT,
  `cost_per_training_hour` INT,
  `cost_annual` INT,
  `feature_sla` VARCHAR(255),
  `feature_support` VARCHAR(255),
  `feature_user_management` VARCHAR(255),
  `is_available` TINYINT(1),
  `is_public` TINYINT(1),
  `is_free` TINYINT(1),
  `export_models_allowed` TINYINT(1),
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `point_cloud` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `original_filename` VARCHAR(255),
  `description` VARCHAR(255),
  `soft_delete` TINYINT(1),
  `url_signed` VARCHAR(255),
  `url_signed_blob_path` VARCHAR(255),
  `url_signed_expiry` VARCHAR(255),
  `url_signed_expiry_force_refresh` VARCHAR(255),
  `service_name` VARCHAR(255),
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `is_public` TINYINT(1),
  `goal` VARCHAR(255),
  `deletion_pending` TINYINT(1),
  `deletion_id` INT,
  `highest_ai_version_number` INT,
  `star_count` INT,
  `latest_issue_number` INT,
  `credit_balance` DOUBLE,
  `project_string_id` VARCHAR(255),
  `user_primary_id` INT,
  `directory_default_id` INT,
  `default_report_dashboard_id` INT,
  `api_billing_enabled` TINYINT(1),
  `annotations_feedback_loop_trigger_check` TINYINT(1),
  `settings_input_video_fps` INT,
  `readme` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `label_dict` VARCHAR(255),
  `cache_dict` VARCHAR(255),
  `default_external_map_id` INT,
  `org_id` INT,
  `account_id` INT,
  `plan_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `default_external_map_id_fkey` FOREIGN KEY (`default_external_map_id`) REFERENCES `external_map` (`id`),
  CONSTRAINT `project_account_id_fkey` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`),
  CONSTRAINT `project_default_report_dashboard_id_fkey` FOREIGN KEY (`default_report_dashboard_id`) REFERENCES `report_dashboard` (`id`),
  CONSTRAINT `project_deletion_id_fkey` FOREIGN KEY (`deletion_id`) REFERENCES `deletion` (`id`),
  CONSTRAINT `project_directory_default_id_fkey` FOREIGN KEY (`directory_default_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `project_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `org` (`id`),
  CONSTRAINT `project_plan_id_fkey` FOREIGN KEY (`plan_id`) REFERENCES `plan` (`id`),
  CONSTRAINT `project_user_primary_id_fkey` FOREIGN KEY (`user_primary_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `ix_project_project_string_id` ON `project` (`project_string_id`);

CREATE TABLE IF NOT EXISTS `project_directory_list` (
  `working_dir_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `nickname` VARCHAR(255),
  `archived` TINYINT(1),
  `created_time` DATETIME(6),
  `last_time` DATETIME(6),
  PRIMARY KEY (`working_dir_id`, `project_id`),
  CONSTRAINT `project_directory_list_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `project_directory_list_working_dir_id_fkey` FOREIGN KEY (`working_dir_id`) REFERENCES `working_dir` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__project_directory_dir_nickname` ON `project_directory_list` (`project_id`, `working_dir_id`, `nickname`);
CREATE INDEX `index__project_directory_list_dir` ON `project_directory_list` (`working_dir_id`);
CREATE INDEX `index__project_directory_list_project` ON `project_directory_list` (`project_id`);

CREATE TABLE IF NOT EXISTS `project_migration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `time_completed` DATETIME(6),
  `time_updated` DATETIME(6),
  `time_last_attempted` DATETIME(6),
  `type` VARCHAR(255),
  `status` VARCHAR(255),
  `percent_complete` DOUBLE,
  `description` VARCHAR(255),
  `external_mapping_project_id` INT,
  `connection_id` INT,
  `error_log` JSON,
  `retry_count` INT,
  `import_schema` TINYINT(1),
  `import_files` TINYINT(1),
  `project_id` INT,
  `migration_log` JSON,
  `member_created_id` INT,
  `member_updated_id` INT,
  `label_schema_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_migration_connection_id_fkey` FOREIGN KEY (`connection_id`) REFERENCES `connection_base` (`id`),
  CONSTRAINT `project_migration_external_mapping_project_id_fkey` FOREIGN KEY (`external_mapping_project_id`) REFERENCES `external_map` (`id`),
  CONSTRAINT `project_migration_label_schema_id_fkey` FOREIGN KEY (`label_schema_id`) REFERENCES `label_schema` (`id`),
  CONSTRAINT `project_migration_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_migration_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_migration_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT,
  `fan_on` TINYINT(1),
  `fan_trigger_interval` INT,
  `fan_inference_size` INT,
  `fan_type` VARCHAR(255),
  `fan_inference_minimum` DOUBLE,
  `fan_method` VARCHAR(255),
  `fan_sub_method` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `project_settings_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_star` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `user_id` INT,
  `project_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_star_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `project_star_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_tag` (
  `project_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `tag_id`),
  CONSTRAINT `project_tag_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `project_tag_tag_id_fkey` FOREIGN KEY (`tag_id`) REFERENCES `tag` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `report_dashboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `diffgram_wide_default` TINYINT(1),
  `project_id` INT,
  `name` VARCHAR(255),
  `archived` TINYINT(1),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `report_dashboard_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `report_dashboard_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `report_dashboard_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `report_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `diffgram_wide_default` TINYINT(1),
  `archived` TINYINT(1),
  `scope` VARCHAR(255),
  `project_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `item_of_interest` VARCHAR(255),
  `group_by` VARCHAR(255),
  `period` VARCHAR(255),
  `date_period_unit` VARCHAR(255),
  `compare_to_previous_period` TINYINT(1),
  `job_id` INT,
  `filter_by_items` VARCHAR(255),
  `report_dashboard_id` INT,
  `is_visible_on_report_dashboard` TINYINT(1),
  `view_type` VARCHAR(255),
  `view_sub_type` VARCHAR(255),
  `task_id` INT,
  `member_list` JSON,
  `group_by_labels` TINYINT(1),
  `task_event_type` VARCHAR(255),
  `second_group_by` VARCHAR(255),
  `aggregate_func` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `report_template_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `report_template_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `report_template_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `report_template_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `report_template_report_dashboard_id_fkey` FOREIGN KEY (`report_dashboard_id`) REFERENCES `report_dashboard` (`id`),
  CONSTRAINT `report_template_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT,
  `name` VARCHAR(255),
  `permissions_list` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `role_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__role_project` ON `role` (`project_id`);

CREATE TABLE IF NOT EXISTS `role_member_object` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT,
  `object_id` INT,
  `object_type` VARCHAR(255),
  `default_role_name` VARCHAR(255),
  `role_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `role_member_object_member_id_fkey` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `role_member_object_role_id_fkey` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__role_user_object_default_role_name` ON `role_member_object` (`default_role_name`);
CREATE INDEX `index__role_user_object_default_role_name_member_id` ON `role_member_object` (`default_role_name`, `member_id`);
CREATE INDEX `index__role_user_object_default_role_name_object_id` ON `role_member_object` (`default_role_name`, `object_id`);
CREATE INDEX `index__role_user_object_member_id` ON `role_member_object` (`member_id`);
CREATE INDEX `index__role_user_object_object_id` ON `role_member_object` (`object_id`);
CREATE INDEX `index__role_user_object_role_id` ON `role_member_object` (`role_id`);
CREATE INDEX `index__role_user_object_role_id_member_id` ON `role_member_object` (`role_id`, `member_id`);
CREATE INDEX `index__role_user_object_role_id_object_id` ON `role_member_object` (`role_id`, `object_id`);

CREATE TABLE IF NOT EXISTS `scheduler_jobs` (
  `id` VARCHAR(255),
  `next_run_time` DOUBLE,
  `job_state` BLOB NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `ix_scheduler_jobs_next_run_time` ON `scheduler_jobs` (`next_run_time`);

CREATE TABLE IF NOT EXISTS `sequence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label_file_id` INT,
  `has_changes` TINYINT(1),
  `single_frame` TINYINT(1),
  `keyframe_list` VARCHAR(255),
  `video_file_id` INT,
  `number` INT,
  `instance_preview_cache` VARCHAR(255),
  `cache_expiry` INT,
  `archived` TINYINT(1),
  PRIMARY KEY (`id`),
  CONSTRAINT `sequence_label_file_id_fkey` FOREIGN KEY (`label_file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `sequence_video_file_id_fkey` FOREIGN KEY (`video_file_id`) REFERENCES `file` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__video_file_id__and__label_file_id` ON `sequence` (`video_file_id`, `label_file_id`);

CREATE TABLE IF NOT EXISTS `signup_code` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255),
  `created_time_int` INT,
  `created_time` DATETIME(6),
  `redeemed_time` DATETIME(6),
  `code` VARCHAR(255),
  `is_available` TINYINT(1),
  `email_sent_to` VARCHAR(255),
  `project_string_id` VARCHAR(255),
  `permission_level` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sync_actions_queue` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `sync_event_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `sync_event_id_fkey` FOREIGN KEY (`sync_event_id`) REFERENCES `sync_event` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sync_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dataset_source_id` INT,
  `dataset_destination_id` INT,
  `created_date` DATETIME(6),
  `description` VARCHAR(255),
  `file_id` INT,
  `job_id` INT,
  `input_id` INT,
  `project_id` INT,
  `created_task_id` INT,
  `completed_task_id` INT,
  `new_file_copy_id` INT,
  `dataset_file_link_copy_id` INT,
  `dataset_file_link_move_id` INT,
  `transfer_action` VARCHAR(255),
  `event_effect_type` VARCHAR(255),
  `event_trigger_type` VARCHAR(255),
  `processing_deferred` TINYINT(1),
  `time_last_attempted` DATETIME(6),
  `status` VARCHAR(255),
  `percent_complete` DOUBLE,
  `member_created_id` INT,
  `member_updated_id` INT,
  `execution_log` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `completed_task_id_fkey` FOREIGN KEY (`completed_task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `created_task_id_fkey` FOREIGN KEY (`created_task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `dataset_destination_id_fkey` FOREIGN KEY (`dataset_destination_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `dataset_source_id_fkey` FOREIGN KEY (`dataset_source_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `input_id_fkey` FOREIGN KEY (`input_id`) REFERENCES `input` (`id`),
  CONSTRAINT `job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `new_file_copy_id_fkey` FOREIGN KEY (`new_file_copy_id`) REFERENCES `file` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `system_configs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `logo_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `image_id_fkey` FOREIGN KEY (`logo_id`) REFERENCES `image` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `system_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kind` VARCHAR(255),
  `description` VARCHAR(255),
  `install_fingerprint` VARCHAR(255),
  `previous_version` VARCHAR(255),
  `diffgram_version` VARCHAR(255),
  `host_os` VARCHAR(255),
  `storage_backend` VARCHAR(255),
  `service_name` VARCHAR(255),
  `startup_time` DATETIME(6),
  `shut_down_time` DATETIME(6),
  `created_date` DATETIME(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_public` TINYINT(1),
  `count` INT,
  `name` VARCHAR(255),
  `project_id` INT,
  `archived` TINYINT(1),
  `color_hex` VARCHAR(255),
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `tag_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `is_live` TINYINT(1),
  `is_root` TINYINT(1),
  `root_id` INT,
  `parent_id` INT,
  `child_primary_id` INT,
  `job_id` INT,
  `kind` VARCHAR(255),
  `task_type` VARCHAR(255),
  `job_type` VARCHAR(255),
  `status` VARCHAR(255),
  `file_original_id` BIGINT,
  `file_id` BIGINT,
  `completion_directory_id` INT,
  `completion_action` VARCHAR(255),
  `guide_id` INT,
  `project_id` INT,
  `label_mode` VARCHAR(255),
  `label_dict` VARCHAR(255),
  `gold_standard_file` VARCHAR(255),
  `assignee_user_id` INT,
  `previous_assignees` JSON,
  `time_created` DATETIME(6),
  `time_completed` DATETIME(6),
  `time_updated` DATETIME(6),
  `count_instances_changed` INT,
  `no_boxes_in_image` TINYINT(1),
  `reviewed_no_changes` TINYINT(1),
  `review_star_rating_average` DOUBLE,
  `gold_standard_missing` INT,
  `incoming_directory_id` INT,
  `default_external_map_id` INT,
  `text_tokenizer` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `default_external_map_id_fkey` FOREIGN KEY (`default_external_map_id`) REFERENCES `external_map` (`id`),
  CONSTRAINT `task_assignee_user_id_fkey` FOREIGN KEY (`assignee_user_id`) REFERENCES `userbase` (`id`),
  CONSTRAINT `task_child_primary_id_fkey` FOREIGN KEY (`child_primary_id`) REFERENCES `task` (`id`),
  CONSTRAINT `task_completion_directory_id_fkey` FOREIGN KEY (`completion_directory_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `task_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `task_file_original_id_fkey` FOREIGN KEY (`file_original_id`) REFERENCES `file` (`id`),
  CONSTRAINT `task_guide_id_fkey` FOREIGN KEY (`guide_id`) REFERENCES `guide` (`id`),
  CONSTRAINT `task_incoming_directory_id_fkey` FOREIGN KEY (`incoming_directory_id`) REFERENCES `working_dir` (`id`),
  CONSTRAINT `task_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `task_parent_id_fkey` FOREIGN KEY (`parent_id`) REFERENCES `task` (`id`),
  CONSTRAINT `task_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__task_file_id` ON `task` (`file_id`);
CREATE INDEX `index__task_job_id` ON `task` (`job_id`);
CREATE INDEX `index__task_project_id` ON `task` (`project_id`);
CREATE INDEX `index__task_status` ON `task` (`status`);
CREATE INDEX `ix_task_project_id` ON `task` (`project_id`);
CREATE INDEX `ix_task_status` ON `task` (`status`);

CREATE TABLE IF NOT EXISTS `task_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_id` INT,
  `project_id` INT,
  `task_id` INT,
  `event_type` VARCHAR(255),
  `comment_id` INT,
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `user_assignee_id` INT,
  `user_reviewer_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `task_event_comment_id_fkey` FOREIGN KEY (`comment_id`) REFERENCES `discussion_comment` (`id`),
  CONSTRAINT `task_event_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `task_event_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `task_event_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `task_event_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `task_event_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `task_event_user_assignee_id_fkey` FOREIGN KEY (`user_assignee_id`) REFERENCES `userbase` (`id`),
  CONSTRAINT `task_event_user_reviewer_id_fkey` FOREIGN KEY (`user_reviewer_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__task_event_job_id` ON `task_event` (`job_id`);
CREATE INDEX `index__task_event_project_id` ON `task_event` (`project_id`);
CREATE INDEX `index__task_event_task_id` ON `task_event` (`task_id`);
CREATE INDEX `task_event_job_id_user_assignee_id` ON `task_event` (`job_id`, `user_assignee_id`);
CREATE INDEX `task_event_job_id_user_reviewer_id` ON `task_event` (`job_id`, `user_reviewer_id`);
CREATE INDEX `task_event_member_created_id` ON `task_event` (`member_created_id`);
CREATE INDEX `task_event_user_assignee_id` ON `task_event` (`user_assignee_id`);
CREATE INDEX `task_event_user_reviewer_id` ON `task_event` (`user_reviewer_id`);

CREATE TABLE IF NOT EXISTS `task_report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `task_time_tracking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT,
  `job_id` INT,
  `project_id` INT,
  `status` VARCHAR(255),
  `user_id` INT,
  `file_id` INT,
  `parent_file_id` INT,
  `time_spent` DOUBLE NOT NULL,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `member_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `task_time_tracking_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `task_time_tracking_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `task_time_tracking_parent_file_id_fkey` FOREIGN KEY (`parent_file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `task_time_tracking_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `task_time_tracking_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `task_time_tracking_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__task_time_tracking_job_id` ON `task_time_tracking` (`job_id`);
CREATE INDEX `index__task_time_tracking_job_id_status` ON `task_time_tracking` (`job_id`, `status`);
CREATE INDEX `index__task_time_tracking_parent_file` ON `task_time_tracking` (`parent_file_id`, `task_id`);
CREATE INDEX `index__task_time_tracking_project_id` ON `task_time_tracking` (`project_id`);
CREATE INDEX `index__task_time_tracking_task_id` ON `task_time_tracking` (`task_id`);
CREATE INDEX `index__task_time_tracking_task_id_status` ON `task_time_tracking` (`task_id`, `status`);
CREATE INDEX `index__task_time_tracking_user_id` ON `task_time_tracking` (`user_id`);

CREATE TABLE IF NOT EXISTS `task_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT,
  `user_id` INT,
  `relation` VARCHAR(255),
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `task_user_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `task_user_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__task_user_task_id` ON `task_user` (`task_id`);
CREATE INDEX `index__task_user_user_id` ON `task_user` (`user_id`);

CREATE TABLE IF NOT EXISTS `text_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `original_filename` VARCHAR(255),
  `description` VARCHAR(255),
  `soft_delete` TINYINT(1),
  `mask_joint_url` VARCHAR(255),
  `mask_joint_blob_name` VARCHAR(255),
  `is_inference` TINYINT(1),
  `annotation_status` VARCHAR(255),
  `is_annotation_example` VARCHAR(255),
  `url_annotation_example` VARCHAR(255),
  `url_public` VARCHAR(255),
  `url_signed` VARCHAR(255),
  `url_signed_blob_path` VARCHAR(255),
  `url_signed_expiry` INT,
  `url_signed_expiry_force_refresh` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `tokens_url_signed` VARCHAR(255),
  `tokens_url_signed_blob_path` VARCHAR(255),
  `tokens_url_signed_expiry` INT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT,
  `transaction_previous_id` INT,
  `transaction_related_id` INT,
  `transaction_type` VARCHAR(255),
  `sub_kind` VARCHAR(255),
  `amount` INT,
  `balance_new` INT,
  `cost_per_instance` INT,
  `count_instances_changed` INT,
  `task_id` INT,
  `job_id` INT,
  `project_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  `audit_cache` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `transaction_account_id_fkey` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`),
  CONSTRAINT `transaction_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `transaction_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `transaction_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `transaction_transaction_previous_id_fkey` FOREIGN KEY (`transaction_previous_id`) REFERENCES `transaction` (`id`),
  CONSTRAINT `transaction_transaction_related_id_fkey` FOREIGN KEY (`transaction_related_id`) REFERENCES `transaction` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ui_schema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `note` VARCHAR(255),
  `version` INT,
  `created_time` DATETIME(6),
  `last_updated_time` DATETIME(6),
  `client_created_time` DATETIME(6),
  `creation_ref_id` VARCHAR(255),
  `deleted_time` DATETIME(6),
  `member_created_id` INT,
  `member_updated_id` INT,
  `project_id` INT,
  `deletion_type` VARCHAR(255),
  `change_source` VARCHAR(255),
  `archived` TINYINT(1),
  `is_visible` TINYINT(1),
  `is_public` TINYINT(1),
  `allowed_instance_type_list` VARCHAR(255),
  `allowed_instance_template_id_list` JSON,
  `global_theme` JSON,
  `logo` JSON,
  `home` JSON,
  `task_list` JSON,
  `undo` JSON,
  `redo` JSON,
  `complete` JSON,
  `defer` JSON,
  `zoom` JSON,
  `label_selector` JSON,
  `instance_selector` JSON,
  `edit_instance_template` JSON,
  `draw_edit` JSON,
  `save` JSON,
  `next_task` JSON,
  `previous_task` JSON,
  `guide` JSON,
  `brightness_contrast_filters` JSON,
  `hotkeys` JSON,
  `overflow_menu` JSON,
  `settings` JSON,
  `attributes` JSON,
  `instances` JSON,
  `userscripts` JSON,
  `nav_bar` JSON,
  `left_bar` JSON,
  `main_canvas` JSON,
  `label_settings` JSON,
  `allow_actions` JSON,
  `block_actions` JSON,
  `time_tracking` JSON,
  `custom_buttons` JSON,
  PRIMARY KEY (`id`),
  CONSTRAINT `member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_follow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `user_id` INT,
  `following_user_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_follow_following_user_id_fkey` FOREIGN KEY (`following_user_id`) REFERENCES `userbase` (`id`),
  CONSTRAINT `user_follow_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_login_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `success` TINYINT(1),
  `otp_success` TINYINT(1),
  `remote_address` VARCHAR(255),
  `user_id` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_login_history_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_to_job` (
  `job_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `status` VARCHAR(255),
  `trainer_auction_payout_per_instance_last` INT,
  `relation` VARCHAR(255),
  PRIMARY KEY (`job_id`, `user_id`, `relation`),
  CONSTRAINT `user_to_job_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `job` (`id`),
  CONSTRAINT `user_to_job_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `userbase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT,
  `qos_last_cached_value` DOUBLE,
  `first_name` VARCHAR(255),
  `last_name` VARCHAR(255),
  `how_hear_about_us` VARCHAR(255),
  `company_name` VARCHAR(255),
  `security_disable_global` TINYINT(1),
  `security_email_verified` TINYINT(1),
  `api_actions` TINYINT(1),
  `api_enabled_builder_brain` TINYINT(1),
  `api_enabled_builder` TINYINT(1),
  `api_enabled_trainer` TINYINT(1),
  `last_builder_or_trainer_mode` VARCHAR(255),
  `phone_number` VARCHAR(255),
  `city` VARCHAR(255),
  `username` VARCHAR(255),
  `email` VARCHAR(255),
  `password_hash` VARCHAR(255),
  `password_attempt_count` INT,
  `auto_commit` TINYINT(1),
  `otp_secret` VARCHAR(255),
  `otp_enabled` TINYINT(1),
  `otp_backup` VARCHAR(255),
  `otp_current_session` VARCHAR(255),
  `otp_current_session_expiry` INT,
  `profile_image_id` INT,
  `profile_image_url` VARCHAR(255),
  `profile_image_blob` VARCHAR(255),
  `profile_image_expiry` INT,
  `profile_image_thumb_url` VARCHAR(255),
  `profile_image_thumb_blob` VARCHAR(255),
  `created_time` DATETIME(6),
  `created_remote_address` VARCHAR(255),
  `last_time` DATETIME(6),
  `current_ai_version_number` INT,
  `current_project_string_id` VARCHAR(255),
  `project_current_id` INT,
  `permissions_projects` VARCHAR(255),
  `permissions_general` VARCHAR(255),
  `is_super_admin` TINYINT(1),
  `last_task_id` INT,
  `available_for_annotation_assignment` TINYINT(1),
  `is_annotator` TINYINT(1),
  `signup_code_id` INT,
  `verify_email_code_id` INT,
  `follow_ing_count` INT,
  `follow_ers_count` INT,
  `signup_role` VARCHAR(255),
  `signup_demo` VARCHAR(255),
  `signup_how_many_data_labelers` VARCHAR(255),
  `occupation_list` VARCHAR(255),
  `linkedin_profile_url` VARCHAR(255),
  `default_plan_id` INT,
  `oidc_id` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `userbase_default_plan_id_fkey` FOREIGN KEY (`default_plan_id`) REFERENCES `plan` (`id`),
  CONSTRAINT `userbase_last_task_id_fkey` FOREIGN KEY (`last_task_id`) REFERENCES `task` (`id`),
  CONSTRAINT `userbase_member_id_fkey` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `userbase_profile_image_id_fkey` FOREIGN KEY (`profile_image_id`) REFERENCES `image` (`id`),
  CONSTRAINT `userbase_project_current_id_fkey` FOREIGN KEY (`project_current_id`) REFERENCES `project` (`id`),
  CONSTRAINT `userbase_signup_code_id_fkey` FOREIGN KEY (`signup_code_id`) REFERENCES `signup_code` (`id`),
  CONSTRAINT `userbase_verify_email_code_id_fkey` FOREIGN KEY (`verify_email_code_id`) REFERENCES `signup_code` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `userbase_project` (
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `working_dir_id` INT,
  `created_time` DATETIME(6),
  `last_time` DATETIME(6),
  PRIMARY KEY (`user_id`, `project_id`),
  CONSTRAINT `userbase_project_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `userbase_project_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`),
  CONSTRAINT `userbase_project_working_dir_id_fkey` FOREIGN KEY (`working_dir_id`) REFERENCES `working_dir` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `userscript` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `archived` TINYINT(1),
  `is_visible` TINYINT(1),
  `is_public` TINYINT(1),
  `name` VARCHAR(255),
  `code` VARCHAR(255),
  `language` VARCHAR(255),
  `external_src_list` VARCHAR(255),
  `use_instructions` VARCHAR(255),
  `docs_link` VARCHAR(255),
  `star_rating_cache` DOUBLE,
  `previous_id` BIGINT,
  `next_id` BIGINT,
  `root_id` BIGINT,
  `version` INT,
  `project_id` INT,
  `client_created_time` DATETIME(6),
  `client_creation_ref_id` VARCHAR(255),
  `member_created_id` INT,
  `member_updated_id` INT,
  `time_created` DATETIME(6),
  `time_updated` DATETIME(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `userscript_member_created_id_fkey` FOREIGN KEY (`member_created_id`) REFERENCES `member` (`id`),
  CONSTRAINT `userscript_member_updated_id_fkey` FOREIGN KEY (`member_updated_id`) REFERENCES `member` (`id`),
  CONSTRAINT `userscript_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `keyframe_list` VARCHAR(255),
  `label_id_map_to_instance_group_id` VARCHAR(255),
  `root_blob_path_to_frames` VARCHAR(255),
  `url_signed_expiry` INT,
  `file_signed_url` VARCHAR(255),
  `file_blob_path` VARCHAR(255),
  `preview_image_url_thumb` VARCHAR(255),
  `preview_image_id` INT,
  `width` INT,
  `height` INT,
  `soft_delete` TINYINT(1),
  `filename` VARCHAR(255),
  `frame_count` INT,
  `description` VARCHAR(255),
  `created_time` DATETIME(6),
  `last_updated_time` DATETIME(6),
  `status` VARCHAR(255),
  `frame_rate` INT,
  `original_fps` INT,
  `fps_conversion_ratio` DOUBLE,
  `offset_in_seconds` INT,
  `parent_video_split_duration` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `video_preview_image_id_fkey` FOREIGN KEY (`preview_image_id`) REFERENCES `image` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `working_dir` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME(6),
  `archived` TINYINT(1),
  `has_changes` TINYINT(1),
  `nickname` VARCHAR(255),
  `count_changes` INT,
  `user_id` INT,
  `file_limit_time` INT,
  `branch_id` INT,
  `project_id` INT,
  `label_file_colour_map` VARCHAR(255),
  `jobs_to_sync` VARCHAR(255),
  `type` VARCHAR(255),
  `default_external_map_id` INT,
  `access_type` VARCHAR(255),
  PRIMARY KEY (`id`),
  CONSTRAINT `default_external_map_id_fkey` FOREIGN KEY (`default_external_map_id`) REFERENCES `external_map` (`id`),
  CONSTRAINT `working_dir_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`),
  CONSTRAINT `working_dir_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `userbase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `index__working_dir_access_type` ON `working_dir` (`access_type`);
CREATE INDEX `index__working_dir_access_type_project` ON `working_dir` (`project_id`, `access_type`);

CREATE TABLE IF NOT EXISTS `workingdir_file_link` (
  `working_dir_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  `type` VARCHAR(255),
  `committed` TINYINT(1),
  `count` INT,
  `created_time` DATETIME(6),
  `last_time` DATETIME(6),
  PRIMARY KEY (`working_dir_id`, `file_id`),
  CONSTRAINT `workingdir_file_link_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`),
  CONSTRAINT `workingdir_file_link_working_dir_id_fkey` FOREIGN KEY (`working_dir_id`) REFERENCES `working_dir` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;

-- +goose Down
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `workingdir_file_link`;
DROP TABLE IF EXISTS `working_dir`;
DROP TABLE IF EXISTS `video`;
DROP TABLE IF EXISTS `userscript`;
DROP TABLE IF EXISTS `userbase_project`;
DROP TABLE IF EXISTS `userbase`;
DROP TABLE IF EXISTS `user_to_job`;
DROP TABLE IF EXISTS `user_login_history`;
DROP TABLE IF EXISTS `user_follow`;
DROP TABLE IF EXISTS `ui_schema`;
DROP TABLE IF EXISTS `transaction`;
DROP TABLE IF EXISTS `text_file`;
DROP TABLE IF EXISTS `task_user`;
DROP TABLE IF EXISTS `task_time_tracking`;
DROP TABLE IF EXISTS `task_report`;
DROP TABLE IF EXISTS `task_event`;
DROP TABLE IF EXISTS `task`;
DROP TABLE IF EXISTS `tag`;
DROP TABLE IF EXISTS `system_events`;
DROP TABLE IF EXISTS `system_configs`;
DROP TABLE IF EXISTS `sync_event`;
DROP TABLE IF EXISTS `sync_actions_queue`;
DROP TABLE IF EXISTS `signup_code`;
DROP TABLE IF EXISTS `sequence`;
DROP TABLE IF EXISTS `scheduler_jobs`;
DROP TABLE IF EXISTS `role_member_object`;
DROP TABLE IF EXISTS `role`;
DROP TABLE IF EXISTS `report_template`;
DROP TABLE IF EXISTS `report_dashboard`;
DROP TABLE IF EXISTS `project_tag`;
DROP TABLE IF EXISTS `project_star`;
DROP TABLE IF EXISTS `project_settings`;
DROP TABLE IF EXISTS `project_migration`;
DROP TABLE IF EXISTS `project_directory_list`;
DROP TABLE IF EXISTS `project`;
DROP TABLE IF EXISTS `point_cloud`;
DROP TABLE IF EXISTS `plan_template`;
DROP TABLE IF EXISTS `plan`;
DROP TABLE IF EXISTS `org_to_user`;
DROP TABLE IF EXISTS `org`;
DROP TABLE IF EXISTS `notification_user`;
DROP TABLE IF EXISTS `notification_relation`;
DROP TABLE IF EXISTS `notification`;
DROP TABLE IF EXISTS `model_run`;
DROP TABLE IF EXISTS `model`;
DROP TABLE IF EXISTS `member`;
DROP TABLE IF EXISTS `label_schema_link`;
DROP TABLE IF EXISTS `label_schema`;
DROP TABLE IF EXISTS `label`;
DROP TABLE IF EXISTS `job_working_dir`;
DROP TABLE IF EXISTS `job_tag`;
DROP TABLE IF EXISTS `job_launch_queue`;
DROP TABLE IF EXISTS `job_launch`;
DROP TABLE IF EXISTS `job`;
DROP TABLE IF EXISTS `instance_template_relation`;
DROP TABLE IF EXISTS `instance_template`;
DROP TABLE IF EXISTS `instance`;
DROP TABLE IF EXISTS `input_batch`;
DROP TABLE IF EXISTS `input`;
DROP TABLE IF EXISTS `image`;
DROP TABLE IF EXISTS `guide`;
DROP TABLE IF EXISTS `geo_asset`;
DROP TABLE IF EXISTS `file_stats`;
DROP TABLE IF EXISTS `file`;
DROP TABLE IF EXISTS `external_map`;
DROP TABLE IF EXISTS `export`;
DROP TABLE IF EXISTS `exam`;
DROP TABLE IF EXISTS `event_hub`;
DROP TABLE IF EXISTS `event`;
DROP TABLE IF EXISTS `discussion_relation`;
DROP TABLE IF EXISTS `discussion_member`;
DROP TABLE IF EXISTS `discussion_comment`;
DROP TABLE IF EXISTS `discussion`;
DROP TABLE IF EXISTS `deletion`;
DROP TABLE IF EXISTS `dataset_tag`;
DROP TABLE IF EXISTS `credential_type_to_job`;
DROP TABLE IF EXISTS `credential_type`;
DROP TABLE IF EXISTS `credential`;
DROP TABLE IF EXISTS `connection_base`;
DROP TABLE IF EXISTS `auth_api`;
DROP TABLE IF EXISTS `audio_file`;
DROP TABLE IF EXISTS `attribute_template_group_to_file`;
DROP TABLE IF EXISTS `attribute_template_group`;
DROP TABLE IF EXISTS `attribute_template`;
DROP TABLE IF EXISTS `alembic_version`;
DROP TABLE IF EXISTS `address`;
DROP TABLE IF EXISTS `activity_interpolation`;
DROP TABLE IF EXISTS `action_template`;
DROP TABLE IF EXISTS `workflow_trigger_event_queue`;
DROP TABLE IF EXISTS `workflow`;
DROP TABLE IF EXISTS `workflow_run`;
DROP TABLE IF EXISTS `action_run`;
DROP TABLE IF EXISTS `action`;
DROP TABLE IF EXISTS `account`;

SET FOREIGN_KEY_CHECKS=1;
